version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Disables version update PRs; security updates still work
    open-pull-requests-limit: 0
    exclude-paths:
      # Copied in from another repo and only used for testing when running the demo
      - "demos/platform/lib/**"
